version: "3.8"

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: medusa_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: medusa-store
      POSTGRES_USER: deadpool
      POSTGRES_PASSWORD: Kroschu.1236547890
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - medusa_network

  # Redis
  redis:
    image: redis:7-alpine
    container_name: medusa_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - medusa_network

  # Medusa Server
  medusa:
    build: .
    container_name: medusa_backend
    restart: unless-stopped
    depends_on:
      - postgres
      - redis
    environment:
      - NODE_ENV=${NODE_ENV:-production}
      - DATABASE_URL=${DATABASE_URL:-postgres://deadpool:Kroschu.1236547890@postgres:5432/medusa-store}
      - REDIS_URL=${REDIS_URL:-redis://redis:6379}
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - medusa_network
      - coolify
    labels:
      - traefik.enable=true
      - traefik.docker.network=coolify

      # Service
      - traefik.http.services.medusa.loadbalancer.server.port=9000

      # HTTPS router
      - traefik.http.routers.medusa-admin.rule=Host(`admin.teherguminet.hu`)
      - traefik.http.routers.medusa-admin.entrypoints=https # or websecure
      - traefik.http.routers.medusa-admin.tls=true
      - traefik.http.routers.medusa-admin.tls.certresolver=letsencrypt
      - traefik.http.routers.medusa-admin.service=medusa # bind router → service
      - traefik.http.routers.medusa-admin.middlewares=medusa-redirect-root

      # HTTP → HTTPS
      - traefik.http.routers.medusa-admin-http.rule=Host(`admin.teherguminet.hu`)
      - traefik.http.routers.medusa-admin-http.entrypoints=http # or web
      - traefik.http.routers.medusa-admin-http.middlewares=medusa-force-https,medusa-redirect-root
      - traefik.http.middlewares.medusa-force-https.redirectscheme.scheme=https
      - traefik.http.middlewares.medusa-force-https.redirectscheme.permanent=true
      - traefik.http.middlewares.medusa-redirect-root.redirectregex.regex=^https?://([^/]+)/(\\?.*)?$
      - traefik.http.middlewares.medusa-redirect-root.redirectregex.replacement=https://$1/app$2
      - traefik.http.middlewares.medusa-redirect-root.redirectregex.permanent=true

volumes:
  postgres_data:

networks:
  medusa_network:
    driver: bridge
  coolify:
    external: true
